# Generated by Django 2.1.7 on 2019-04-25 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.TextField(max_length=5)),
                ('device_type', models.TextField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.TextField(blank=True, max_length=12)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('check', 'Check'), ('cash', 'Cash')], default='check', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(max_length=20)),
                ('order_size', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdap', models.TextField(max_length=8)),
                ('part_type', models.TextField(max_length=16)),
                ('quoteCost', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_notes', models.TextField(max_length=500)),
                ('repaired_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('part_used', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='RepairTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.TextField(max_length=5)),
                ('issue', models.TextField(max_length=500)),
                ('serial_number', models.TextField(max_length=12)),
                ('device_owner', models.TextField()),
                ('ticket_number', models.TextField(max_length=5)),
                ('comments', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='repairticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.RepairTicket'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Repair'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='repairticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.RepairTicket'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Order'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.PartType'),
        ),
    ]
