# Generated by Django 2.1.7 on 2019-04-28 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [



        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.TextField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.TextField(max_length=20)),
                ('device', models.TextField(max_length=20)),
                ('order', models.TextField(max_length=20)),
                ('part_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.TextField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairticket', models.TextField(max_length=20)),
                ('repair', models.TextField(max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('charged', models.DecimalField(decimal_places=2, max_digits=4)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('check', 'Check'), ('cash', 'Cash')], default='check', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.TextField(max_length=20)),
                ('order_size', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=4)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdap', models.TextField(max_length=8)),
                ('part_type', models.TextField(max_length=16)),
                ('quoteCost', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repairticket', models.TextField(max_length=20)),
                ('repair_notes', models.TextField(max_length=500)),
                ('part_used', models.TextField(max_length=20)),
                ('repaired_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RepairTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.TextField(max_length=5)),
                ('issue', models.TextField(max_length=500)),
                ('serial_number', models.TextField(max_length=12)),
                ('device_owner', models.TextField()),
                ('ticket_number', models.TextField(max_length=5)),
                ('comments', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
