# Generated by Django 2.1.7 on 2019-03-26 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_cost', models.TextField(max_length=10)),
                ('device_type', models.CharField(max_length=12)),
                ('part_type', models.CharField(max_length=18)),
                ('color', models.CharField(max_length=12)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateTimeField()),
                ('repaired_on', models.DateTimeField()),
                ('returned_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('charged', models.TextField(max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('order_size', models.PositiveIntegerField()),
                ('part_price', models.TextField(max_length=10)),
                ('shipping_price', models.TextField(max_length=10)),
                ('tax_price', models.TextField(max_length=10)),
                ('total_cost', models.TextField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_notes', models.TextField(max_length=500)),
                ('repaired_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('part_used', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='RepairTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.PositiveIntegerField()),
                ('issue', models.TextField(max_length=500)),
                ('serial_number', models.TextField(max_length=12)),
                ('device_owner', models.TextField()),
                ('ticket_number', models.PositiveIntegerField()),
                ('comments', models.TextField(max_length=500)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='repairticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='refurbco.RepairTicket'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='repair',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Repair'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='repairticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='refurbco.RepairTicket'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='order_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Order'),
        ),
    ]
