# Generated by Django 2.1.7 on 2019-03-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repairticket',
            name='model_number',
            field=models.TextField(max_length=4),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='ticket_number',
            field=models.TextField(max_length=5),
        ),
    ]
