# Generated by Django 2.1.7 on 2019-04-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.TextField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.TextField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='device_owner',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='issue',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='repairticket',
            name='ticket_number',
            field=models.TextField(blank=True, max_length=5),
        ),
    ]
