# Generated by Django 2.1.7 on 2019-04-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0002_auto_20190428_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='device',
            name='model_number',
            field=models.TextField(max_length=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Repair'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='repairticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.RepairTicket'),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='quoteCost',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='repair',
            name='part_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Inventory'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repairticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.RepairTicket'),
        ),
    ]
