# Generated by Django 2.1.7 on 2019-04-18 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0003_auto_20190326_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='part_price',
            new_name='shipping',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_price',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax_price',
            new_name='tax',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='total',
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_number',
            field=models.TextField(default='what is this', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device_type',
            field=models.TextField(max_length=16),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Order'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_type',
            field=models.CharField(max_length=16),
        ),
    ]
