# Generated by Django 2.1.7 on 2019-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0003_auto_20190428_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_size',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.TextField(max_length=20),
        ),
    ]
