# Generated by Django 2.1.7 on 2019-04-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0004_auto_20190428_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='mdap',
            field=models.TextField(blank=True, max_length=8),
        ),
    ]
