# Generated by Django 2.1.7 on 2019-04-23 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0006_auto_20190423_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttype',
            name='color',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.PartType'),
        ),
    ]
