# Generated by Django 2.1.7 on 2019-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0007_auto_20190423_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device_type',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='mdap',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_cost',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_type',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='used',
            field=models.TextField(max_length=20),
        ),
    ]
