# Generated by Django 2.1.7 on 2019-04-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0008_auto_20190425_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Device'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='mdap',
            field=models.TextField(max_length=8),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.Order'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_cost',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='refurbco.PartType'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
