# Generated by Django 2.1.7 on 2019-04-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0009_auto_20190425_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='device_type',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='order_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_type',
            field=models.TextField(max_length=20),
        ),
    ]
