# Generated by Django 2.1.7 on 2019-04-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0010_auto_20190425_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='mdap',
        ),
        migrations.AlterField(
            model_name='repair',
            name='part_used',
            field=models.TextField(max_length=20),
        ),
    ]
