# Generated by Django 2.1.7 on 2019-04-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0011_auto_20190425_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repairticket',
            field=models.TextField(max_length=20),
        ),
    ]
