# Generated by Django 2.1.7 on 2019-04-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0012_auto_20190425_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='repair',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='repairticket',
            field=models.TextField(max_length=20),
        ),
    ]
