# Generated by Django 2.1.7 on 2019-04-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refurbco', '0016_auto_20190425_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='color',
            field=models.TextField(max_length=12),
        ),
    ]
